name: Futurerestore

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

jobs:
  macOS:
    runs-on: macos-14
    env:
      PROCURSUS: /opt/procursus
      PATH: /opt/procursus/bin:/opt/procursus/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Install Homebrew (if not present)
        run: |
          if ! command -v brew >/dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
            eval "$(/opt/homebrew/bin/brew shellenv)"
          fi
      - name: Setup Homebrew PATH
        run: |
          if [ -x /opt/homebrew/bin/brew ]; then
            eval "$(/opt/homebrew/bin/brew shellenv)"
            echo "PATH=$PATH" >> $GITHUB_ENV
          elif [ -x /usr/local/bin/brew ]; then
            eval "$(/usr/local/bin/brew shellenv)"
            echo "PATH=$PATH" >> $GITHUB_ENV
          else
            echo "Homebrew not found!" >&2
            exit 1
          fi
      - name: Install CMake and dependencies
        run: |
          brew tap aderuelle/homebrew-tap
          brew tap stek29/homebrew-idevice 
          brew update
          brew install aderuelle/tap/img4tool
          brew install libusbmuxd cmake libplist libirecovery libzip autoconf automake libtool pkg-config libtatsu openssl libgeneral libipatcher
      - name: Build libimobiledevice from source (if needed)
        run: |
          git clone https://github.com/libimobiledevice/libimobiledevice.git
          cd libimobiledevice
          ./autogen.sh --prefix=/usr/local --enable-debug
          make && sudo make install
      - name: Build and install libfragmentzip from source
        run: |
          git clone https://github.com/thehtml5gameguy/libfragmentzip.git
          cd libfragmentzip
          ./autogen.sh
          make
          sudo make install

      - name: Run macOS Bootstrap Script
        run: ${{ github.workspace }}/.github/workflows/mac-bootstrap.sh

      - name: Run macOS Build Script
        run: ${{ github.workspace }}/.github/workflows/mac-build.sh

      - name: Run macOS Post Script
        run: ${{ github.workspace }}/.github/workflows/mac-post.sh

      - name: Upload Versioning Info
        uses: actions/upload-artifact@v4
        with:
          name: Versioning
          path: |
            ${{ github.workspace }}/latest_build_sha.txt
            ${{ github.workspace }}/latest_build_num.txt

      - name: Upload macOS RELEASE Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-macOS-RELEASE
          path: ${{ github.workspace }}/futurerestore-macOS-*-RELEASE.tar.xz

      - name: Upload macOS DEBUG Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-macOS-DEBUG
          path: ${{ github.workspace }}/futurerestore-macOS-*-DEBUG.tar.xz

      - name: Upload macOS ASAN Archive
        uses: actions/upload-artifact@v4
        with:
          name: futurerestore-macOS-ASAN
          path: ${{ github.workspace }}/futurerestore-macOS-*-ASAN.tar.xz
